services:
  portal-agro-postgres-prod:
    image: postgres:16
    container_name: portal-agro-postgres-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal-agro_prod
    ports:
      - "5435:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - network_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30

  portal-agro-api-prod:
    image: portal-agro-api-prod:latest
    container_name: portal-agro-api-prod
    restart: always
    env_file:
      - .env
    depends_on:
      portal-agro-postgres-prod:
        condition: service_healthy
    ports:
      - "5103:8080"
    networks:
      - network_prod
    labels:
      - com.portal-agro.environment=prod

volumes:
  pgdata_prod:

networks:
  network_prod:
    driver: bridge
