# Quita "version:" (obsoleta en Compose v2)

services:
  portal-agro-api-develop:
    container_name: portal-agro-api-develop
    build:
      context: ../..   # ← workspace raíz (dos niveles arriba desde DevOps/develop)
      dockerfile: Portal-Agro-comercial-del-Huila/Web/Dockerfile
    image: portal-agro-api-develop:latest   # etiqueta útil para referenciar/depurar
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - portal-agro_network
    labels:
      - com.portalagro.environment=develop

networks:
  portal-agro_network:
    external: true
