services:
  portal-agro-api-develop:
    container_name: portal-agro-api-develop
    build:
      context: ../../Portal-Agro-comercial-del-Huila   # ← entra directo a la carpeta del proyecto
      dockerfile: Web/Dockerfile                       # ← relativo al context, sin prefijos repetidos
    image: portal-agro-api-develop:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - portal-agro_network
    labels:
      - com.portalagro.environment=develop

networks:
  portal-agro_network:
    external: true
