services:
  portal-agro-api-develop:
    container_name: portal-agro-api-develop
    build:
      context: ../../../                # ← raíz del repo
      dockerfile: Portal-Agro-comercial-del-Huila/Web/Dockerfile
    image: portal-agro-api-develop:latest
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production

      # DB
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=PortalAgroDb;User Id=sa;Password=Admin123.;Encrypt=False;TrustServerCertificate=True
      - MIGRATE_SQLSERVER=true

      # ===== SMTP / Gmail =====
      - CONFIG_EMAIL__EMAIL=portalagrocomercialhuila@gmail.com
      - CONFIG_EMAIL__HOST=smtp.gmail.com
      - CONFIG_EMAIL__PORT=587
      # ATENCIÓN: las contraseñas de app de Google se usan SIN espacios
      - CONFIG_EMAIL__PASSWORD=qtckwqqwgnmarosr
      # 587 => STARTTLS
      - CONFIG_EMAIL__USESTARTTLS=true
      - CONFIG_EMAIL__USESSL=false
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - portal-agro_network
    labels:
      - com.portalagro.environment=develop

networks:
  portal-agro_network:
    external: true
