version: "3.9"

services:
  # 🌐 API principal - DEVELOP
  portal-agro-api-develop:
    container_name: portal-agro-api-develop
    build:
      context: ../..
      dockerfile: Web/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - portal-agro_network
    labels:
      - com.portal-agro.environment=develop

networks:
  portal-agro_network:
    external: true