services:
  portal-agro-api-develop:
    container_name: portal-agro-api-develop
    build:
      context: ../../Portal-Agro-comercial-del-Huila/Web
      dockerfile: Dockerfile
    image: portal-agro-api-develop:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - portal-agro_network
    labels:
      - com.portalagro.environment=develop

networks:
  portal-agro_network:
    external: true
